language:
  php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s https://getcomposer.org/installer | php -- --install-dir="assignment1_part2"
  - php ./assignment1_part2/composer.phar -v -o -d=assignment1_part2/ update

script:
  - php assignment1_part2/vendor/bin/phpunit --coverage-text -c assignment1_part2/Test/Conf/phpunit.xml

