#
# .travis.yml for Lab 5, for WebLAMP 442.
#
# This travis file installs composer in assignment1_part2,
# updates it, and then runs the tests for that project.
#
# Important details:
#   - Composer's installer can take an --install-dir parameter.
#   - Install/update for composer can have a work directory, -d.
#

language:
  php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s https://getcomposer.org/installer | php -- --install-dir="assignment1_part2"
  - php ./assignment1_part2/composer.phar -v -o -d=assignment1_part2/ update

script:
  - php assignment1_part2/vendor/bin/phpunit --coverage-text -c assignment1_part2/Test/Conf/phpunit.xml

