language:
  php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php ./composer.phar -v -o update

script:
  - php vendor/bin/phpunit --coverage-text -c Tests/Conf/phpunit.xml

